repos:
  - repo: local
    hooks:
      - id: updatemd
        name: Update diagrams in markdown files
        entry: python3 tools/uml4md/updatemd.py
        language: python
        files: \.md$
        stages: [commit]
        verbose: true
        require_serial: true
        fail_fast: false
